/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseHeader: typeof import('./components/layouts/BaseHeader.vue')['default']
    BaseSide: typeof import('./components/layouts/BaseSide.vue')['default']
    CustomIcon: typeof import('./components/ZsIcon/components/CustomIcon.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTag: typeof import('element-plus/es')['ElTag']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Index11: typeof import('./components/ZsIcon/index11.vue')['default']
    Index222: typeof import('./components/ZsIcon/index222.vue')['default']
    SubMenu: typeof import('./components/ZsMenu/components/SubMenu.vue')['default']
    ZsAppMain: typeof import('./components/ZsAppMain/index.vue')['default']
    ZsContainer: typeof import('./components/ZsContainer/index.vue')['default']
    ZsIcon: typeof import('./components/ZsIcon/index.vue')['default']
    ZsLogo: typeof import('./components/ZsLogo/index.vue')['default']
    ZsMenu: typeof import('./components/ZsMenu/index.vue')['default']
    ZsNavBar: typeof import('./components/ZsNavBar/index.vue')['default']
    ZsSelectIcon: typeof import('./components/ZsSelectIcon/index.vue')['default']
  }
}
