/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseHeader: typeof import('./../components/layouts/BaseHeader.vue')['default']
    BaseSide: typeof import('./../components/layouts/BaseSide.vue')['default']
    CustomIcon: typeof import('./../components/ZsIcon/components/CustomIcon.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    EmptyList: typeof import('./../components/ZsFeedback/empty-list.vue')['default']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    Index11: typeof import('./../components/ZsIcon/index11.vue')['default']
    Index222: typeof import('./../components/ZsIcon/index222.vue')['default']
    Index3333: typeof import('./../components/ZsIcon/index3333.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubMenu: typeof import('./../components/ZsMenu/components/SubMenu.vue')['default']
    ZsAppMain: typeof import('./../components/ZsAppMain/index.vue')['default']
    ZsContainer: typeof import('./../components/ZsContainer/index.vue')['default']
    ZsIcon: typeof import('./../components/ZsIcon/index.vue')['default']
    ZsLogo: typeof import('./../components/ZsLogo/index.vue')['default']
    ZsMenu: typeof import('./../components/ZsMenu/index.vue')['default']
    ZsNavBar: typeof import('./../components/ZsNavBar/index.vue')['default']
    ZsSelectIcon: typeof import('./../components/ZsSelectIcon/index.vue')['default']
  }
}
